using AlpineSim.Core.Fleet;
using AlpineSim.Core.Math;
using AlpineSim.Core.Sim;
using AlpineSim.Core.Tasks;
using AlpineSim.Core.Vehicles;
using NUnit.Framework;

namespace AlpineSim.Tests.Tasks
{
    /// <summary>
    /// The night foreman: he staffs only the machine he gives the job to, he does not offer a job straight back to
    /// the machine that handed it in, and he judges a climb by what the machine can hold in the snow lying there.
    /// </summary>
    [TestFixture]
    public sealed class ForemanDispatchTests
    {
        private static AlpineSim.Core.Data.GameData Data()
        {
            var data = TestEnv.FreshData();
            data.Tuning.Override("tasks.autoDispatch", 0f); // these tests call the foreman by hand
            return data;
        }

        private static VehicleState Cat(Simulation sim)
        {
            foreach (var v in sim.World.Vehicles.List) if (v.DefId == "groomer_mid") return v;
            Assert.Fail("test_small has no groomer_mid");
            return null;
        }

        /// <summary>Everyone but the named operator is taken off the roster, so the fleet holds exactly one cat driver.</summary>
        private static OperatorState OnlyCatDriver(Simulation sim)
        {
            var f = sim.World.Fleet;
            OperatorState keep = null;
            foreach (var o in f.Operators) if (!o.IsPlayer && o.Has(OperatorLicense.Groomer)) { keep = o; break; }
            Assert.IsNotNull(keep, "test_small has no groomer-licensed operator");
            for (int i = f.Operators.Count - 1; i >= 0; i--)
            {
                var o = f.Operators[i];
                if (o.IsPlayer || o.Id == keep.Id) continue;
                f.Operators.RemoveAt(i);
            }
            return keep;
        }

        /// <summary>
        /// Two cats, one licensed driver, one grooming job: the job goes out. Staffing every candidate during the
        /// scan used to shuffle the one driver from cat to cat, and the cat finally picked had lost her again, so the
        /// job stayed open night after night with a driver parked at the depot.
        /// </summary>
        [Test]
        public void OneDriverAndTwoCatsStillGetsTheJobOut()
        {
            var sim = Simulation.CreateNew(Data(), 41, "test_small");
            var ctx = sim.Ctx;
            var ts = sim.GetSystem<TaskSystem>();
            var vs = sim.GetSystem<VehicleSystem>();
            OnlyCatDriver(sim);

            // the second cat stands FARTHER from the run than the first, so the nearest-wins scan picks the first.
            // That is the case the old scan broke on: staffing each candidate in turn moved the one driver off the
            // first cat and into the second, and the first - the one the scan then picked - had nobody in it.
            var first = Cat(sim);
            var piste = sim.World.Pistes.Piste("t1");
            var site = piste.Points[piste.Points.Count - 1];
            var away = (first.Pos - site).Normalized;
            var second = vs.Spawn(ctx, "groomer_mid", first.Pos + away * 60f, 0f, "Second Cat");
            Assert.AreEqual(-1, first.OperatorId);
            Assert.AreEqual(-1, second.OperatorId);
            Assert.Less(Vec2.Distance(first.Pos, site), Vec2.Distance(second.Pos, site), "the first cat must be the nearer one");

            // top priority so it outranks the road and lot work the sim posts on its own
            var task = ts.Create(ctx, TaskKind.Groom, "Groom " + piste.Name, site, "t1", -1, 1f, 9f);
            task.AutoGenerated = true;

            ts.AutoDispatch(ctx);
            Assert.AreNotEqual(-1, task.AssignedVehicleId, "the foreman should give the job to one of the two cats");
            Assert.AreEqual(TaskStatus.InProgress, task.Status);

            var sent = task.AssignedVehicleId == first.Id ? first : second;
            Assert.AreNotEqual(-1, task.AssignedVehicleId, "the job was assigned to no machine");
            Assert.AreNotEqual(-1, sent.OperatorId, "the cat that got the job has nobody in it");
            var op = sim.World.Fleet.Operator(sent.OperatorId);
            Assert.IsTrue(op.Has(OperatorLicense.Groomer), "the cat that got the job holds an unlicensed operator");

            var idle = sent.Id == first.Id ? second : first;
            Assert.AreEqual(-1, idle.OperatorId, "the driver was left sitting in the cat that did not get the job");
        }

        /// <summary>A machine that hands a job in is not offered it again on the same shift: it would drive to the same pitch and stall there again.</summary>
        [Test]
        public void AJobHandedInIsNotOfferedBackToTheSameMachine()
        {
            var sim = Simulation.CreateNew(Data(), 42, "test_small");
            var ctx = sim.Ctx;
            var ts = sim.GetSystem<TaskSystem>();
            var fs = sim.GetSystem<FleetSystem>();
            var cat = Cat(sim);
            OnlyCatDriver(sim);

            var piste = sim.World.Pistes.Piste("t1");
            var task = ts.Create(ctx, TaskKind.Groom, "Groom " + piste.Name, piste.Points[piste.Points.Count - 1], "t1", -1, 1f, 9f);
            task.AutoGenerated = true;

            ts.AutoDispatch(ctx);
            Assert.AreEqual(cat.Id, task.AssignedVehicleId);

            // the cat gives it back on a pitch it cannot climb
            ts.Unassign(ctx, task.Id);
            ts.Block(ctx, task.Id, cat.Name + ": cannot climb the 22 deg pitch", cat.Id);
            Assert.AreEqual(cat.Id, task.BlockedByVehicleId);

            // the retry timer runs out and the job goes back on the board, but not to that cat
            ts.Unblock(ctx, task.Id);
            Assert.AreEqual(TaskStatus.Open, task.Status);
            ts.AutoDispatch(ctx);
            Assert.AreEqual(-1, task.AssignedVehicleId, "the cat that handed the job in was sent straight back to it");

            // by the next shift it is offered again
            sim.StepHours(ctx.Tuning.F("tasks.blockRetrySameMachineHours") + 0.5);
            Assert.AreEqual(TaskStatus.Open, task.Status, "the job should still be open");
            ts.AutoDispatch(ctx);
            Assert.AreEqual(cat.Id, task.AssignedVehicleId, "after the shift window the cat should be offered the job again");
        }

        /// <summary>
        /// A later block for another reason - a wind hold, a machine throwing a track on the same job - must not erase
        /// the record of which machine handed the job in, nor restart its clock.
        /// </summary>
        [Test]
        public void AWeatherHoldDoesNotEraseTheSameMachineHold()
        {
            var sim = Simulation.CreateNew(Data(), 49, "test_small");
            var ctx = sim.Ctx;
            var ts = sim.GetSystem<TaskSystem>();
            var cat = Cat(sim);
            OnlyCatDriver(sim);

            var piste = sim.World.Pistes.Piste("t1");
            var task = ts.Create(ctx, TaskKind.Groom, "Groom " + piste.Name, piste.Points[piste.Points.Count - 1], "t1", -1, 1f, 9f);
            task.AutoGenerated = true;

            ts.Block(ctx, task.Id, cat.Name + ": cannot climb the 22 deg pitch", cat.Id);
            long handedIn = task.BlockedByTick;
            Assert.AreEqual(cat.Id, task.BlockedByVehicleId);
            Assert.GreaterOrEqual(handedIn, 0L);

            sim.StepMinutes(30);
            ts.Block(ctx, task.Id, "weather: wind hold"); // names no machine
            Assert.AreEqual(cat.Id, task.BlockedByVehicleId, "the wind hold erased the record of who handed the job in");
            Assert.AreEqual(handedIn, task.BlockedByTick, "the wind hold restarted the same-machine clock");

            ts.Unblock(ctx, task.Id);
            ts.AutoDispatch(ctx);
            Assert.AreEqual(-1, task.AssignedVehicleId, "the cat that handed the job in should still be held out");
        }

        /// <summary>A job blocked for a reason that is nobody's machine (weather, parts) is not excluded from any machine.</summary>
        [Test]
        public void AJobBlockedWithoutAMachineIsOfferedToEveryone()
        {
            var sim = Simulation.CreateNew(Data(), 43, "test_small");
            var ctx = sim.Ctx;
            var ts = sim.GetSystem<TaskSystem>();
            var cat = Cat(sim);
            OnlyCatDriver(sim);

            var piste = sim.World.Pistes.Piste("t1");
            var task = ts.Create(ctx, TaskKind.Groom, "Groom " + piste.Name, piste.Points[piste.Points.Count - 1], "t1", -1, 1f, 9f);
            task.AutoGenerated = true;
            ts.Block(ctx, task.Id, "weather: wind hold"); // no machine named
            Assert.AreEqual(-1, task.BlockedByVehicleId);
            ts.Unblock(ctx, task.Id);

            ts.AutoDispatch(ctx);
            Assert.AreEqual(cat.Id, task.AssignedVehicleId, "a weather hold must not exclude the fleet");
        }

        /// <summary>
        /// A refuel call is never held back from the only truck that can go: a machine stranded on the hill does not
        /// wait out a shift because the truck turned back once.
        /// </summary>
        [Test]
        public void ARescueCallIsNeverHeldBackFromTheMachineThatTurnedBack()
        {
            var sim = Simulation.CreateNew(Data(), 47, "test_small");
            var ctx = sim.Ctx;
            var ts = sim.GetSystem<TaskSystem>();
            VehicleState truck = null;
            foreach (var v in sim.World.Vehicles.List) if (v.DefId == "service_truck") truck = v;
            Assert.IsNotNull(truck, "test_small has no service truck");

            var call = ts.Create(ctx, TaskKind.Refuel, "Refuel Test Cat", truck.Pos + new Vec2(20f, 0f), "1", -1, 1f, 9f);
            call.AutoGenerated = true;
            ts.AutoDispatch(ctx);
            Assert.AreEqual(truck.Id, call.AssignedVehicleId, "the service truck should take the refuel call");

            // the truck turns back, and the call goes straight back on the board
            ts.Unassign(ctx, call.Id);
            ts.Block(ctx, call.Id, truck.Name + ": slope above the operator's rating", truck.Id);
            ts.Unblock(ctx, call.Id);

            ts.AutoDispatch(ctx);
            Assert.AreEqual(truck.Id, call.AssignedVehicleId, "a stranded machine must not wait a shift for fuel");
        }

        /// <summary>
        /// The grade a machine can hold comes from the snow it is standing in, not from its rating: deep fresh snow
        /// and worn tracks both take it away. A cat that climbs its rated pitch on corduroy stalls on the same pitch
        /// under thirty centimetres of new snow.
        /// </summary>
        [Test]
        public void ClimbLimitFallsWithFreshSnowAndWornTracks()
        {
            var sim = Simulation.CreateNew(Data(), 44, "test_small");
            var ctx = sim.Ctx;
            var vs = sim.GetSystem<VehicleSystem>();
            var cat = Cat(sim);
            var grid = sim.World.Snow;

            var groomed = new Vec2(256f, 200f);
            var fresh = new Vec2(256f, 240f);
            int gid = grid.EnsureCellAt(groomed), fid = grid.EnsureCellAt(fresh);
            Assert.GreaterOrEqual(gid, 0); Assert.GreaterOrEqual(fid, 0);

            grid.LooseMm[gid] = 0f; grid.PackedMm[gid] = 600f; grid.Density[gid] = 520f;   // corduroy
            grid.LooseMm[fid] = 300f; grid.PackedMm[fid] = 300f; grid.Density[fid] = 480f; // 30 cm of new snow on top

            cat.Condition.WearTracks = 0f;
            float onCorduroy = vs.ClimbLimitDeg(ctx, cat, groomed);
            float inFresh = vs.ClimbLimitDeg(ctx, cat, fresh);
            Assert.Greater(onCorduroy, inFresh, "deep fresh snow must cost the machine climb");
            Assert.Greater(onCorduroy, 15f, "a cat on packed corduroy should hold a real pitch");
            Assert.Greater(inFresh, 0f, "the limit must stay positive and finite");

            cat.Condition.WearTracks = 1f;
            float worn = vs.ClimbLimitDeg(ctx, cat, groomed);
            Assert.Less(worn, onCorduroy, "worn tracks must cost the machine climb");
            Assert.GreaterOrEqual(worn, 0f);
        }

        /// <summary>
        /// A machine whose rolling resistance beats its traction cannot move at all, on the flat or down a gentle
        /// grade. The climb limit goes negative to say so, and no route is passable for it - a flat one included.
        /// </summary>
        [Test]
        public void AMachineThatCannotMoveHasNoPassableRoute()
        {
            var sim = Simulation.CreateNew(Data(), 50, "test_small");
            var ctx = sim.Ctx;
            var vs = sim.GetSystem<VehicleSystem>();
            var cat = Cat(sim);
            var grid = sim.World.Snow;

            var spot = cat.Pos;
            int id = grid.EnsureCellAt(spot);
            grid.LooseMm[id] = 1000f; grid.PackedMm[id] = 0f; grid.Density[id] = 120f;
            cat.Condition.WearTracks = 1f;

            Assert.Less(vs.ClimbLimitDeg(ctx, cat, spot), 0f, "buried in a metre of unconsolidated snow the cat cannot move");

            // a level hop across the same ground is not passable either
            var flat = new System.Collections.Generic.List<Vec2> { spot, spot + new Vec2(6f, 0f) };
            Assert.IsFalse(vs.RouteWithinTraction(ctx, cat, flat, out float shortfall), "a stuck machine was waved through a flat route");
            Assert.Greater(shortfall, 0f);
        }

        /// <summary>Snow on the mouldboard is dragged up the pitch as well as carried, so it costs the machine climb.</summary>
        [Test]
        public void ALoadedBladeCostsClimb()
        {
            var sim = Simulation.CreateNew(Data(), 51, "test_small");
            var ctx = sim.Ctx;
            var vs = sim.GetSystem<VehicleSystem>();
            var cat = Cat(sim);
            var grid = sim.World.Snow;

            var spot = cat.Pos;
            int id = grid.EnsureCellAt(spot);
            grid.LooseMm[id] = 0f; grid.PackedMm[id] = 600f; grid.Density[id] = 520f;
            cat.Condition.WearTracks = 0f;

            AlpineSim.Core.Vehicles.MountedAttachment blade = null;
            foreach (var m in cat.Mounted) { var a = ctx.Data.Attachment(m.DefId); if (a != null && a.Kind.IsBlade()) { blade = m; break; } }
            Assert.IsNotNull(blade, "the cat should carry a blade");

            blade.LoadKg = 0f;
            float empty = vs.ClimbLimitDeg(ctx, cat, spot);
            blade.LoadKg = 2500f;
            float loaded = vs.ClimbLimitDeg(ctx, cat, spot);
            Assert.Less(loaded, empty, "a windrow on the blade must cost the machine climb");
            blade.LoadKg = 0f;
        }

        /// <summary>A transit limit is never above what the machine is rated for, however good the grip.</summary>
        [Test]
        public void TransitLimitNeverExceedsTheMachineRating()
        {
            var sim = Simulation.CreateNew(Data(), 45, "test_small");
            var ctx = sim.Ctx;
            var vs = sim.GetSystem<VehicleSystem>();
            var cat = Cat(sim);
            int id = sim.World.Snow.EnsureCellAt(cat.Pos);
            sim.World.Snow.LooseMm[id] = 0f; sim.World.Snow.PackedMm[id] = 800f; sim.World.Snow.Density[id] = 520f;
            cat.Condition.WearTracks = 0f;

            float rated = ctx.Data.Vehicle(cat.DefId).MaxGradeDeg + ctx.Tuning.F("vehicles.aiSlopeMarginDeg");
            Assert.LessOrEqual(vs.TransitClimbLimitDeg(ctx, cat), rated + 0.001f);
        }

        /// <summary>
        /// A machine buried in snow it cannot grip is not handed a straight line over the nearest headwall. The route
        /// graph answers an impossible query with a bee-line from A to B, and slope refusal is switched off on the way
        /// home, so an unchecked answer would drive the cat into a ridge until it parked itself stuck.
        /// </summary>
        [Test]
        public void ARouteHomeFallsBackToTheRatedRouteRatherThanABeeLine()
        {
            var sim = Simulation.CreateNew(Data(), 48, "test_small");
            var ctx = sim.Ctx;
            var vs = sim.GetSystem<VehicleSystem>();
            var cat = Cat(sim);
            var grid = sim.World.Snow;

            // a metre of unconsolidated snow under the tracks: the machine can hold almost nothing
            int id = grid.EnsureCellAt(cat.Pos);
            grid.LooseMm[id] = 1000f; grid.PackedMm[id] = 0f; grid.Density[id] = 120f;
            cat.Condition.WearTracks = 1f;
            Assert.Less(vs.TransitClimbLimitDeg(ctx, cat), 5f, "buried and worn, the cat should hold almost no grade");

            // a target far enough that the graph is consulted at all, and uphill, so the climb limit bites
            var piste = sim.World.Pistes.Piste("t1");
            var top = piste.Points[0];
            Assert.Greater(Vec2.Distance(cat.Pos, top), ctx.Tuning.F("vehicles.routeStraightMaxM"), "the target must be beyond a straight hop");

            var planned = vs.FindRouteWithinTraction(ctx, cat, top);
            Assert.IsNotNull(planned);
            Assert.GreaterOrEqual(planned.Count, 2);

            // either the planned route is one the machine can actually hold, or it is exactly the rated route it
            // would have driven before - never a bee-line the traction search degraded into
            bool holdable = vs.RouteWithinTraction(ctx, cat, planned, out _);
            if (!holdable)
            {
                var rated = vs.FindRoute(ctx, cat, top);
                Assert.AreEqual(rated.Count, planned.Count, "a degraded traction search must fall back to the rated route");
                for (int i = 0; i < rated.Count; i++)
                {
                    Assert.AreEqual(rated[i].X, planned[i].X, 0.001f);
                    Assert.AreEqual(rated[i].Y, planned[i].Y, 0.001f);
                }
                Assert.Greater(planned.Count, 2, "the rated route across the map should be a real graph route, not a straight line");
            }
        }

        /// <summary>A route over ground the machine cannot hold is reported, with the shortfall in degrees.</summary>
        [Test]
        public void RouteWithinTractionReportsTheWorstShortfall()
        {
            var sim = Simulation.CreateNew(Data(), 46, "test_small");
            var ctx = sim.Ctx;
            var vs = sim.GetSystem<VehicleSystem>();
            var cat = Cat(sim);

            var flat = new System.Collections.Generic.List<Vec2> { cat.Pos, cat.Pos + new Vec2(6f, 0f) };
            Assert.IsTrue(vs.RouteWithinTraction(ctx, cat, flat, out float shortfall), "a six-metre hop on the pad should be fine");
            Assert.AreEqual(0f, shortfall, 0.001f);

            Assert.IsFalse(vs.RouteWithinTraction(ctx, cat, null, out float none), "a route that could not be found is not passable");
            Assert.AreEqual(0f, none, 0.001f);
        }
    }
}
