using System;
using System.Collections.Generic;
using AlpineSim.Core.Math;
using AlpineSim.Core.Vehicles;

namespace AlpineSim.Core.Tasks
{
    public enum TaskStatus { Open, Assigned, InProgress, Blocked, Done, Cancelled }

    /// <summary>
    /// A job on the mountain ("groom Village Run", "clear Lot B", "set tower 7"). Declares the roles
    /// and licence it needs; the task system tells the player which machines can take it.
    /// Work is measured in units defined by the kind (m² groomed, towers set, m³ delivered, ...).
    /// </summary>
    [Serializable]
    public sealed class WorkTask
    {
        public int Id;
        public TaskKind Kind = TaskKind.Custom;
        public string Title = "";
        public List<VehicleRole> RequiredRoles = new List<VehicleRole>();
        public OperatorLicense RequiredLicense = OperatorLicense.Basic;
        public Vec2 Site;
        public float SiteRadiusM = 12f;
        /// <summary>Piste, zone, lift, vehicle or gun id the task acts on.</summary>
        public string TargetId = "";
        /// <summary>Tower index, segment index, etc.</summary>
        public int TargetIndex = -1;
        public float WorkRequired = 1f;
        public float WorkDone;
        public TaskStatus Status = TaskStatus.Open;
        public int AssignedVehicleId = -1;
        public int AssignedOperatorId = -1;
        public string BlockReason = "";
        /// <summary>Tick the task was last blocked at; auto-generated jobs reopen after tasks.blockRetryMinutes.</summary>
        public long BlockedTick = -1;
        public long CreatedTick;
        public long DeadlineTick = -1;
        public long CompletedTick = -1;
        public float Priority = 1f;
        /// <summary>For haul tasks: where to load, and how much (kg or m³) to deliver.</summary>
        public Vec2 LoadAt;
        public string LoadAtId = "";
        public float QuantityRequired;
        public float QuantityDelivered;
        public string CargoKind = "";
        public int ProjectId = -1;
        public bool PlayerCreated;
        public bool AutoGenerated;
        public string Notes = "";

        public float Progress => WorkRequired <= 0f ? 1f : (WorkDone / WorkRequired < 1f ? WorkDone / WorkRequired : 1f);
        public bool IsActive => Status == TaskStatus.Open || Status == TaskStatus.Assigned || Status == TaskStatus.InProgress || Status == TaskStatus.Blocked;
    }

    [Serializable]
    public sealed class TaskBoardState
    {
        public List<WorkTask> Tasks = new List<WorkTask>();
        public int NextId = 1;
        public int CompletedTotal;

        public WorkTask Get(int id)
        {
            for (int i = 0; i < Tasks.Count; i++) if (Tasks[i].Id == id) return Tasks[i];
            return null;
        }
    }

    public struct TaskCreatedEvent { public int TaskId; }
    public struct TaskAssignedEvent { public int TaskId; public int VehicleId; public int OperatorId; }
    public struct TaskCompletedEvent { public int TaskId; public TaskKind Kind; public string TargetId; public int ProjectId; }
    public struct TaskBlockedEvent { public int TaskId; public string Reason; }
    public struct TaskCancelledEvent { public int TaskId; }
}

namespace AlpineSim.Core.Tasks
{
    /// <summary>Eligibility of one machine for a task, for the fleet and task screens.</summary>
    public struct TaskCandidate
    {
        public int VehicleId;
        public bool Eligible;
        public string Reason;
    }
}
