#!/usr/bin/env python3
"""Regenerates docs/TUNING.md from Assets/StreamingAssets/Data/tuning.json.

Every anchor in tuning.json carries value, min, max, unit and comment (its real-world basis);
this tool renders them as one table per group so the document can never drift from the data.

    python3 tools/gen_tuning_doc.py          # rewrite docs/TUNING.md
    python3 tools/gen_tuning_doc.py --check  # exit 1 if docs/TUNING.md is stale (CI)
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TUNING = os.path.join(ROOT, "Assets", "StreamingAssets", "Data", "tuning.json")
DOC = os.path.join(ROOT, "docs", "TUNING.md")

HEADER = """# Tuning anchors

Every balance number lives in `Assets/StreamingAssets/Data/tuning.json` (plus the per-record
tables in `vehicles.json`, `attachments.json`, `lifts.json`, `guests.json`, `economy.json`,
`climate.json`, `construction.json`, `stations.json`, `tasks.json`, `operators.json`). Keys are
dotted paths read in code through `ctx.Tuning.F("group.key")`, `.I(...)` or `.Curve(key, x)`;
a missing key throws, so there are no silent fallbacks in C#.

Each anchor carries its allowed range and the real-world basis it was taken from. This file is
generated by `python3 tools/gen_tuning_doc.py`; edit `tuning.json`, not this document.

"""


def fmt(v):
    if isinstance(v, bool):
        return "1" if v else "0"
    if isinstance(v, float):
        s = ("%.6f" % v).rstrip("0").rstrip(".")
        return s if s else "0"
    if isinstance(v, list):
        return "[" + ", ".join(fmt(x) for x in v) + "]"
    return str(v)


def esc(s):
    return str(s).replace("|", "\\|").replace("\n", " ")


def render():
    with open(TUNING, encoding="utf-8") as f:
        data = json.load(f)
    out = [HEADER]
    total = 0
    for group, entries in data.items():
        if group == "comment" or not isinstance(entries, dict):
            continue
        out.append("## `%s`\n\n" % group)
        if isinstance(entries.get("comment"), str):
            out.append(entries["comment"] + "\n\n")
        out.append("| Key | Value | Range | Unit | Basis |\n| --- | --- | --- | --- | --- |\n")
        for key, a in entries.items():
            if key == "comment" or not isinstance(a, dict):
                continue
            total += 1
            if "xs" in a:
                value = "curve xs=%s ys=%s" % (fmt(a.get("xs")), fmt(a.get("ys")))
                rng = "-"
            else:
                value = fmt(a.get("value"))
                rng = "%s .. %s" % (fmt(a.get("min", "")), fmt(a.get("max", "")))
            out.append("| `%s.%s` | %s | %s | %s | %s |\n" % (group, key, value, rng, esc(a.get("unit", "")), esc(a.get("comment", ""))))
        out.append("\n")
    out.append("_%d anchors._\n" % total)
    return "".join(out)


def main():
    text = render()
    if "--check" in sys.argv:
        current = open(DOC, encoding="utf-8").read() if os.path.exists(DOC) else ""
        if current != text:
            print("docs/TUNING.md is stale; run python3 tools/gen_tuning_doc.py")
            return 1
        print("TUNING.md up to date")
        return 0
    with open(DOC, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print("wrote", os.path.relpath(DOC, ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
